[package]
name = "scope-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true

[[bin]]
name = "scope"
path = "src/main.rs"

[dependencies]
blake3.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
scope-core = { path = "../scope-core" }
tokio.workspace = true
rustyline.workspace = true
